### ISSUE TITLE
FlatBuffer Panic With VALIDATE Set

### ISSUE THREAD

**Issue by pascaldekloe** [alecthomas/go_serialization_benchmarks#33]
% go version
go version go1.5 darwin/amd64
% VALIDATE=1 go test -bench='.*' ./

A test suite for benchmarking various Go serialization methods.

See README.md for details on running the benchmarks.

PASS
BenchmarkVmihailencoMsgpackMarshal-8  	 1000000	      2076 ns/op	     400 B/op	       6 allocs/op
BenchmarkVmihailencoMsgpackUnmarshal-8	  500000	      2901 ns/op	     496 B/op	      15 allocs/op
BenchmarkJsonMarshal-8                	  500000	      2563 ns/op	     584 B/op	       7 allocs/op
BenchmarkJsonUnmarshal-8              	  300000	      5071 ns/op	     559 B/op	      10 allocs/op
BenchmarkBsonMarshal-8                	 1000000	      1600 ns/op	     416 B/op	      10 allocs/op
BenchmarkBsonUnmarshal-8              	--- FAIL: BenchmarkBsonUnmarshal-8
	serialization_benchmarks_test.go:315: unmarshaled object differed:
		&{6ba41ebd83bd6a7c 2015-09-09 20:22:05.735954112 +0200 CEST 788dc877a6 4 false 0.49660976898283055}
		&{6ba41ebd83bd6a7c 2015-09-09 20:22:05.735 +0200 CEST 788dc877a6 4 false 0.49660976898283055}
BenchmarkVitessBsonMarshal-8          	 1000000	      1062 ns/op	    1168 B/op	       4 allocs/op
BenchmarkVitessBsonUnmarshal-8        	--- FAIL: BenchmarkVitessBsonUnmarshal-8
	serialization_benchmarks_test.go:315: unmarshaled object differed:
		&{0561b476f8f2f9f9 2015-09-09 20:22:06.822174012 +0200 CEST 8342e65f20 4 false 0.12722105587509064}
		&{0561b476f8f2f9f9 2015-09-09 18:22:06.822 +0000 UTC 8342e65f20 4 false 0.12722105587509064}
BenchmarkGobMarshal-8                 	  200000	      7609 ns/op	    1808 B/op	      35 allocs/op
BenchmarkGobUnmarshal-8               	   50000	     34900 ns/op	    9424 B/op	     239 allocs/op
BenchmarkXdrMarshal-8                 	 1000000	      2000 ns/op	     591 B/op	      20 allocs/op
BenchmarkXdrUnmarshal-8               	  500000	      2535 ns/op	     383 B/op	      13 allocs/op
BenchmarkUgorjiCodecMsgpackMarshal-8  	  500000	      2522 ns/op	    1905 B/op	      10 allocs/op
BenchmarkUgorjiCodecMsgpackUnmarshal-8	  500000	      3654 ns/op	    1984 B/op	      16 allocs/op
BenchmarkUgorjiCodecBincMarshal-8     	  500000	      2536 ns/op	    1937 B/op	      10 allocs/op
BenchmarkUgorjiCodecBincUnmarshal-8   	--- FAIL: BenchmarkUgorjiCodecBincUnmarshal-8
	serialization_benchmarks_test.go:315: unmarshaled object differed:
		&{e80460e8f0256208 2015-09-09 20:22:18.400028604 +0200 CEST 206396d044 3 false 0.4436151940429639}
		&{e80460e8f0256208 2015-09-09 20:22:18.400028604 +0200 +0200 206396d044 3 false 0.4436151940429639}
BenchmarkSerealMarshal-8              	  500000	      3769 ns/op	     928 B/op	      21 allocs/op
BenchmarkSerealUnmarshal-8            	  300000	      4563 ns/op	    1248 B/op	      36 allocs/op
BenchmarkBinaryMarshal-8              	 1000000	      1658 ns/op	     352 B/op	      16 allocs/op
BenchmarkBinaryUnmarshal-8            	  500000	      2753 ns/op	     544 B/op	      24 allocs/op
BenchmarkMsgpMarshal-8                	 5000000	       321 ns/op	     144 B/op	       1 allocs/op
BenchmarkMsgpUnmarshal-8              	 1000000	      1384 ns/op	     208 B/op	       5 allocs/op
BenchmarkGoprotobufMarshal-8          	 2000000	       649 ns/op	     320 B/op	       4 allocs/op
BenchmarkGoprotobufUnmarshal-8        	 2000000	       905 ns/op	     432 B/op	       9 allocs/op
BenchmarkGogoprotobufMarshal-8        	10000000	       179 ns/op	      64 B/op	       1 allocs/op
BenchmarkGogoprotobufUnmarshal-8      	 5000000	       285 ns/op	     112 B/op	       3 allocs/op
BenchmarkProtobufMarshal-8            	 1000000	      1120 ns/op	     224 B/op	       7 allocs/op
BenchmarkProtobufUnmarshal-8          	 1000000	      1868 ns/op	     336 B/op	      12 allocs/op
BenchmarkHproseMarshal-8              	 1000000	      1070 ns/op	     495 B/op	       8 allocs/op
BenchmarkHproseUnmarshal-8            	 1000000	      2254 ns/op	     416 B/op	      12 allocs/op
BenchmarkFlatbuffersMarshal-8         	 5000000	       340 ns/op	       0 B/op	       0 allocs/op
BenchmarkFlatBuffersUnmarshal-8       	panic: runtime error: slice bounds out of range

goroutine 33 [running]:
github.com/google/flatbuffers/go.(*Table).Offset(0xc820053e58, 0xc, 0x1)
	/Users/pkloe/Code/pascaldekloe/src/github.com/google/flatbuffers/go/table.go:15 +0x1b5
bu.(*FlatBufferA).Spouse(0xc820053e58, 0x1)
	/Users/pkloe/Code/pascaldekloe/src/bu/FlatBufferA.go:51 +0x33
bu.BenchmarkFlatBuffersUnmarshal(0xc820144000)
	/Users/pkloe/Code/pascaldekloe/src/bu/serialization_benchmarks_test.go:632 +0x4d2
testing.(*B).runN(0xc820144000, 0x1)
	/usr/local/go/src/testing/benchmark.go:124 +0x9a
testing.(*B).launch(0xc820144000)
	/usr/local/go/src/testing/benchmark.go:199 +0x63
created by testing.(*B).run
	/usr/local/go/src/testing/benchmark.go:179 +0x54

goroutine 1 [runnable]:
testing.(*B).run(0xc820144000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/testing/benchmark.go:180 +0x7b
testing.RunBenchmarks(0x874798, 0xa94440, 0x20, 0x20)
	/usr/local/go/src/testing/benchmark.go:332 +0x75f
testing.(*M).Run(0xc82004fef8, 0xffffffff)
	/usr/local/go/src/testing/testing.go:503 +0x1b8
main.main()
	bu/_test/_testmain.go:118 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2
FAIL	bu	47.598s

**Comment by pascaldekloe** [comment]
Fixed with Go 1.5.1
