### ISSUE TITLE
panic: not implemented

### ISSUE THREAD

**Issue by havok4u** [alecthomas/go_serialization_benchmarks#89]
I am using version 3.11.4 of protocol buffers and Go 1.14.2
```
$ protoc --version
libprotoc 3.11.4
```

When running 
`$ go test -bench='.*' ./`

I get the following
A test suite for benchmarking various Go serialization methods.

See README.md for details on running the benchmarks.

```
goos: linux
goarch: amd64
pkg: github.com/alecthomas/go_serialization_benchmarks
BenchmarkGotinyMarshal-8                        	13304299	        89.4 ns/op	        48.0 B/serial	       0 B/op	       0 allocs/op
BenchmarkGotinyUnmarshal-8                      	 6830947	       178 ns/op	        48.0 B/serial	     112 B/op	       3 allocs/op
BenchmarkGotinyNoTimeMarshal-8                  	12590604	        89.3 ns/op	        48.0 B/serial	       0 B/op	       0 allocs/op
BenchmarkGotinyNoTimeUnmarshal-8                	 7424698	       160 ns/op	        48.0 B/serial	      96 B/op	       3 allocs/op
BenchmarkMsgpMarshal-8                          	 9219133	       132 ns/op	        97.0 B/serial	     128 B/op	       1 allocs/op
BenchmarkMsgpUnmarshal-8                        	 4838880	       234 ns/op	        97.0 B/serial	     112 B/op	       3 allocs/op
BenchmarkVmihailencoMsgpackMarshal-8            	 1556703	       753 ns/op	       100 B/serial	     288 B/op	       4 allocs/op
BenchmarkVmihailencoMsgpackUnmarshal-8          	 1289294	       942 ns/op	       100 B/serial	     160 B/op	       9 allocs/op
BenchmarkJsonMarshal-8                          	  504692	      2342 ns/op	       152 B/serial	     944 B/op	       6 allocs/op
BenchmarkJsonUnmarshal-8                        	  467035	      2513 ns/op	       152 B/serial	     344 B/op	       6 allocs/op
BenchmarkJsonIterMarshal-8                      	  813463	      1338 ns/op	       152 B/serial	     952 B/op	       7 allocs/op
BenchmarkJsonIterUnmarshal-8                    	  515895	      2167 ns/op	       152 B/serial	     447 B/op	      14 allocs/op
BenchmarkEasyJsonMarshal-8                      	 1000000	      1111 ns/op	       152 B/serial	     784 B/op	       5 allocs/op
BenchmarkEasyJsonUnmarshal-8                    	 1089238	      1091 ns/op	       152 B/serial	     160 B/op	       4 allocs/op
BenchmarkBsonMarshal-8                          	 1269421	       884 ns/op	       110 B/serial	     392 B/op	      10 allocs/op
BenchmarkBsonUnmarshal-8                        	  926041	      1277 ns/op	       110 B/serial	     244 B/op	      19 allocs/op
BenchmarkGobMarshal-8                           	 2198652	       549 ns/op	        63.6 B/serial	      48 B/op	       2 allocs/op
BenchmarkGobUnmarshal-8                         	 2226387	       588 ns/op	        63.7 B/serial	     112 B/op	       3 allocs/op
BenchmarkXDRMarshal-8                           	  942240	      1265 ns/op	        92.0 B/serial	     455 B/op	      20 allocs/op
BenchmarkXDRUnmarshal-8                         	 1000000	      1085 ns/op	        92.0 B/serial	     239 B/op	      11 allocs/op
BenchmarkUgorjiCodecMsgpackMarshal-8            	 1342996	       882 ns/op	        91.0 B/serial	    1312 B/op	       3 allocs/op
BenchmarkUgorjiCodecMsgpackUnmarshal-8          	 1333430	       962 ns/op	        91.0 B/serial	     496 B/op	       4 allocs/op
BenchmarkUgorjiCodecBincMarshal-8               	 1216729	       950 ns/op	        95.0 B/serial	    1328 B/op	       4 allocs/op
BenchmarkUgorjiCodecBincUnmarshal-8             	 1000000	      1061 ns/op	        95.0 B/serial	     640 B/op	       7 allocs/op
BenchmarkSerealMarshal-8                        	  613936	      2004 ns/op	       132 B/serial	     904 B/op	      20 allocs/op
BenchmarkSerealUnmarshal-8                      	  509361	      2359 ns/op	       132 B/serial	    1008 B/op	      34 allocs/op
BenchmarkBinaryMarshal-8                        	 1000000	      1063 ns/op	        61.0 B/serial	     326 B/op	      21 allocs/op
BenchmarkBinaryUnmarshal-8                      	 1000000	      1118 ns/op	        61.0 B/serial	     320 B/op	      22 allocs/op
BenchmarkFlatBuffersMarshal-8                   	 5044725	       236 ns/op	        95.2 B/serial	       0 B/op	       0 allocs/op
BenchmarkFlatBuffersUnmarshal-8                 	 6249824	       191 ns/op	        95.2 B/serial	     112 B/op	       3 allocs/op
BenchmarkCapNProtoMarshal-8                     	 3490287	       309 ns/op	        96.0 B/serial	      56 B/op	       2 allocs/op
BenchmarkCapNProtoUnmarshal-8                   	 3719278	       332 ns/op	        96.0 B/serial	     200 B/op	       6 allocs/op
BenchmarkCapNProto2Marshal-8                    	 2531958	       539 ns/op	        96.0 B/serial	     244 B/op	       3 allocs/op
BenchmarkCapNProto2Unmarshal-8                  	 2005264	       631 ns/op	        96.0 B/serial	     320 B/op	       6 allocs/op
BenchmarkHproseMarshal-8                        	 1711749	       659 ns/op	        85.3 B/serial	     353 B/op	       8 allocs/op
BenchmarkHproseUnmarshal-8                      	 1392330	       869 ns/op	        85.3 B/serial	     319 B/op	      10 allocs/op
BenchmarkHprose2Marshal-8                       	 2824647	       427 ns/op	        85.3 B/serial	       0 B/op	       0 allocs/op
BenchmarkHprose2Unmarshal-8                     	 2624437	       442 ns/op	        85.3 B/serial	     144 B/op	       4 allocs/op
BenchmarkProtobufMarshal-8                      	 2087547	       569 ns/op	        52.0 B/serial	     152 B/op	       7 allocs/op
BenchmarkProtobufUnmarshal-8                    	 1331026	       904 ns/op	        52.0 B/serial	     280 B/op	      16 allocs/op
panic: not implemented

goroutine 169 [running]:
github.com/golang/protobuf/proto.(*InternalMessageInfo).Size(...)
	/home/tepkes/Development/Go/pkg/mod/github.com/golang/protobuf@v1.4.0/proto/deprecated.go:91
github.com/alecthomas/go_serialization_benchmarks.(*ProtoBufA).XXX_Size(0xc00073ce60, 0xe8f240)
	/home/tepkes/Projects/Serialization/go_serialization_benchmarks/structdef.pb.go:52 +0x39
github.com/gogo/protobuf/proto.Marshal(0xe8f240, 0xc00073ce60, 0x21c, 0x5eb00fab, 0xc000421ef8, 0x48b936, 0x5eb00fab)
	/home/tepkes/Development/Go/pkg/mod/github.com/gogo/protobuf@v1.3.1/proto/table_marshal.go:2938 +0x278
github.com/alecthomas/go_serialization_benchmarks.BenchmarkGoprotobufMarshal(0xc0000d4540)
	/home/tepkes/Projects/Serialization/go_serialization_benchmarks/serialization_benchmarks_test.go:830 +0xd6
testing.(*B).runN(0xc0000d4540, 0x1)
	/usr/lib/go-1.14/src/testing/benchmark.go:191 +0xe8
testing.(*B).run1.func1(0xc0000d4540)
	/usr/lib/go-1.14/src/testing/benchmark.go:231 +0x57
created by testing.(*B).run1
	/usr/lib/go-1.14/src/testing/benchmark.go:224 +0x7d
exit status 2
FAIL	github.com/alecthomas/go_serialization_benchmarks	62.291s
FAIL
```

**Comment by alecthomas** [comment]
I can't reproduce this, but I suspect this is because you're not using Go modules and your package versions aren't being pinned correctly.
